### ISSUE TITLE
Coverage during e2e test

### ISSUE THREAD

**Issue by jclaveau** [jclaveau/strapi-provider-upload-google-drive#19]
### Goals
- [ ] Know the current coverage of the plugin
- [ ] Be able to run auto-dependencies update without breaking the plugin

### Todo
- [ ] Playwright only supports coverage for front js with Chrome 
  - [ ] Install Isambul with Playwright
    - https://tech.xriba.io/2022/04/26/exploring-e2e-testing-and-code-coverage-with-playwright/
    - https://github.com/bgotink/playwright-coverage
  - [ ] Handle google connection with Cromium browser (unsafe browser issue)
- [ ] Run Strapi with Istambul
  - [ ] Investigate node:cluster with Istambul: How istambul handles subprocesses?
    - https://nodejs.org/api/cluster.html#how-it-works
    - https://github.com/istanbuljs/nyc
    - https://github.com/strapi/strapi/blob/2e44e15bc7d29756a6e0ee0b29ac50378f0a1328/packages/core/strapi/lib/commands/develop.js#L49
  - [ ] Start Playwright test project with Istambul
- [ ] Send Coverage to CI pipe
  - [ ] Readme badge
