### ISSUE TITLE
OAuth clientId and secret from provider config

### ISSUE THREAD

**Issue by jclaveau** [jclaveau/strapi-provider-upload-google-drive#3]
### Goal
- [x] Do not show Google client ID/Secret to other superadmins
- [x] Set per environment drive

### Scuccess Criteria
- [x] Do not save config in settings
- [ ] 

### Todo
- [x] Rename the current config service as settingsService
- [x] Add a configService to access plugin's config
- [x] Hide client / secret if taken from config
- [x] add dumpConfig entry to config for dev purpose to hide dump section in settings page
- [x] use client / secrets from config if defined
- [x] Update the README
- [ ] Test env with values set from plugin config
