### ISSUE TITLE
Replace file url as API with redirections / local cache

### ISSUE THREAD

**Issue by jclaveau** [jclaveau/strapi-provider-upload-google-drive#4]
### Goal
- [x] Use HTTP cache
- [x] The existing uploads must work if the user stops using this provider (cached files in /public)

### Todo
- [x] Investigate Design
    - Create a middlewar around Strapi's public middleware https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/middlewares/public/index.js
    - https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/middlewares.html#internal-middlewares-configuration-reference
    - https://docs.strapi.io/developer-docs/latest/developer-resources/plugin-api-reference/server.html#middlewares
    - If the file is missing, try to download it from GDrive
 - [x] Update the path of the image to target regular asset folder
 - [x] Store the cached files as if they have been uploaded with the default provider (filename~gdrive_id.ext)
 - [x] ensure delete works
 - [x] update the readme
